import { type ClassValue, clsx } from "clsx";
import { twMerge } from "tailwind-merge";

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

// Mock Data for Data-X Platform

export type ResourceType = "API" | "Agent" | "Dataset";
export type PricingType = "Free" | "Paid" | "Freemium";

export interface Resource {
  id: string;
  title: string;
  description: string;
  provider: string;
  type: ResourceType;
  price: PricingType;
  priceAmount?: string;
  tags: string[];
  image?: string;
  publishedDate: string;
  views: number;
  featured?: boolean;
  specs?: {
    format: string;
    frequency: string;
    access: string;
  };
  longDescription?: string;
  useCases?: string[];
}

export const RESOURCES: Resource[] = [
  // AI Assistant
  {
    id: "1",
    title: "ChatGPT Assistant Agent",
    description: "AI-powered conversational agent for customer support and internal knowledge base queries.",
    provider: "NextWave Automation",
    type: "Agent",
    price: "Paid",
    tags: ["AI Assistant", "automation", "chat"],
    image: "ai_agent_icon_abstract",
    publishedDate: "2025-07-13",
    views: 1240,
    featured: true,
    specs: { format: "JSON/REST", frequency: "Real-time", access: "API Key" }
  },
  // Customer Service
  {
    id: "2",
    title: "ChatBot Agent Pro",
    description: "Advanced customer service bot with sentiment analysis and escalation protocols.",
    provider: "ServiceTech",
    type: "Agent",
    price: "Paid",
    tags: ["Customer Service", "support", "bot"],
    publishedDate: "2025-08-20",
    views: 980
  },
  {
    id: "3",
    title: "Customer Support Agent Lite",
    description: "Lightweight support agent for small businesses.",
    provider: "ServiceTech",
    type: "Agent",
    price: "Paid",
    tags: ["Customer Service", "support", "smb"],
    publishedDate: "2025-09-01",
    views: 450
  },
  // Manufacturing
  {
    id: "4",
    title: "Industrial Sensor Data",
    description: "Raw sensor data from manufacturing plants for predictive maintenance analysis.",
    provider: "ManufacturingCore Tech",
    type: "API",
    price: "Paid",
    tags: ["Manufacturing", "iot", "sensor"],
    image: "iot_data_icon_abstract",
    publishedDate: "2025-11-15",
    views: 856
  },
  // AI/ML
  {
    id: "5",
    title: "GPT-4 API",
    description: "Advanced language model API for natural language processing and generation.",
    provider: "OpenAI",
    type: "API",
    price: "Paid",
    tags: ["AI/ML", "nlp", "generation"],
    publishedDate: "2025-11-27",
    views: 486
  },
  {
    id: "6",
    title: "Vision Model V2",
    description: "Computer vision model for object detection and classification.",
    provider: "Visionary AI",
    type: "API",
    price: "Paid",
    tags: ["AI/ML", "vision", "image"],
    publishedDate: "2025-10-12",
    views: 320
  },
  // Analytics
  {
    id: "7",
    title: "Data Analytics Agent",
    description: "Automated data analyst that generates insights from raw CSV uploads.",
    provider: "DataMind",
    type: "Agent",
    price: "Paid",
    tags: ["Analytics", "insight", "reporting"],
    publishedDate: "2025-09-15",
    views: 1100
  },
  {
    id: "8",
    title: "Unified Analytics Platform",
    description: "Comprehensive dashboarding API for cross-platform metrics.",
    provider: "MetricStream",
    type: "API",
    price: "Freemium",
    tags: ["Analytics", "dashboard", "metrics"],
    publishedDate: "2025-10-01",
    views: 750
  },
  // Finance
  {
    id: "9",
    title: "Financial Data API",
    description: "Real-time stock market and cryptocurrency data feed.",
    provider: "FinTech Solutions",
    type: "API",
    price: "Freemium",
    tags: ["Finance", "market", "stocks"],
    image: "financial_data_icon_abstract",
    publishedDate: "2025-10-08",
    views: 2100
  },
  // Financial Services
  {
    id: "10",
    title: "Financial Market Intelligence",
    description: "Deep dive analysis reports generated by AI agents on market trends.",
    provider: "QuantumFinance",
    type: "Agent",
    price: "Paid",
    tags: ["Financial Services", "intelligence", "report"],
    publishedDate: "2025-10-20",
    views: 1500
  },
  // Operations
  {
    id: "11",
    title: "Operations Co-Pilot",
    description: "AI assistant for managing daily operational workflows and scheduling.",
    provider: "OpsGenie",
    type: "Agent",
    price: "Paid",
    tags: ["Operations", "workflow", "management"],
    publishedDate: "2025-11-05",
    views: 600
  },
  // Transport
  {
    id: "12",
    title: "Public Transit Schedule",
    description: "Real-time bus and subway schedules for major metropolitan areas.",
    provider: "CityTransport",
    type: "Dataset",
    price: "Free",
    tags: ["Transport", "public", "schedule"],
    publishedDate: "2025-11-27",
    views: 4100
  },
  // Transportation
  {
    id: "13",
    title: "Logistics Route Optimizer",
    description: "API for optimizing delivery routes based on traffic and weather conditions.",
    provider: "LogiTech",
    type: "API",
    price: "Paid",
    tags: ["Transportation", "logistics", "routing"],
    publishedDate: "2025-09-30",
    views: 890
  },
  // Weather
  {
    id: "14",
    title: "Global Weather API",
    description: "Current weather, forecasts, and historical data for any location.",
    provider: "MeteoGlobal",
    type: "API",
    price: "Freemium",
    tags: ["Weather", "forecast", "climate"],
    publishedDate: "2025-11-27",
    views: 4300
  },
  {
    id: "15",
    title: "OpenWeather API",
    description: "Simple and fast weather API for developers.",
    provider: "OpenWeather",
    type: "API",
    price: "Freemium",
    tags: ["Weather", "simple", "fast"],
    publishedDate: "2025-11-20",
    views: 3200
  },
  // Artificial Intelligence
  {
    id: "16",
    title: "Multi-Agent AI Systems",
    description: "Orchestration platform for multiple specialized AI agents.",
    provider: "NextWave",
    type: "Agent",
    price: "Paid",
    tags: ["Artificial Intelligence", "orchestration", "multi-agent"],
    publishedDate: "2025-07-13",
    views: 1500
  },
  // Industrial IoT
  {
    id: "17",
    title: "Industrial IoT Data Stream",
    description: "High-frequency sensor data stream for industrial machinery.",
    provider: "IoTech",
    type: "API",
    price: "Freemium",
    tags: ["Industrial IoT", "stream", "machinery"],
    publishedDate: "2025-11-15",
    views: 900
  }
];

export interface BlogPost {
  id: string;
  title: string;
  excerpt: string;
  author: string;
  date: string;
  category: string;
  readTime: string;
  imageGradient: string;
}

export const BLOG_POSTS: BlogPost[] = [
  {
    id: "1",
    title: "Multi-Agent AI Systems: Why Teams of AIs Beat Solo Models",
    excerpt: "Single agents hit a ceiling. Multi-agent systems scale by orchestrating specialized AIs that collaborate in real time.",
    author: "Nikolas Barwicki",
    date: "Nov 20, 2025",
    category: "AI Agents",
    readTime: "5 min read",
    imageGradient: "from-purple-500 to-indigo-600",
  },
  {
    id: "2",
    title: "How to Build an MCP Server in 15 Minutes",
    excerpt: "A practical guide to spinning up your first Model Context Protocol server with real endpoints and auth.",
    author: "Dev Team",
    date: "Nov 18, 2025",
    category: "Tutorial",
    readTime: "10 min read",
    imageGradient: "from-emerald-500 to-teal-600",
  },
  {
    id: "3",
    title: "Is RAG Still Relevant in 2026?",
    excerpt: "What retrieval-augmented generation is great at, where it breaks, and how to layer tools and agents on top.",
    author: "Research Lab",
    date: "Nov 12, 2025",
    category: "Research",
    readTime: "8 min read",
    imageGradient: "from-blue-500 to-cyan-600",
  },
  {
    id: "4",
    title: "Voice AI Agents: The Definitive Guide",
    excerpt: "Latency budgets, streaming architectures, and evaluation tips for production-ready voice agents.",
    author: "Audio Team",
    date: "Oct 21, 2025",
    category: "Deep Dive",
    readTime: "12 min read",
    imageGradient: "from-orange-500 to-red-600",
  }
];
